name: clipboard_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  isar_community_flutter_libs: ^3.3.0
  isar_community: ^3.3.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  isar_community_generator: ^3.3.0

flutter:
  uses-material-design: true
